"""Sigma-style detection rule exporter.

Rather than try to round-trip arbitrary Sigma, we emit a single behavior-based
rule that fires when ANY of the high-confidence selectors match. This is a
useful starting point for an analyst, not a finished rule.
"""
from __future__ import annotations

import uuid
from pathlib import Path

from analystbridge.exports.common import utc_now_iso
from analystbridge.ui.services import AnalysisBundle


def _rule_uuid(sample_id: str) -> str:
    # Stable per-sample so re-running export doesn't churn the rule's UUID.
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"analystbridge:{sample_id}"))


def _attack_tags(mappings) -> list[str]:
    tags = ["attack"]
    for m in mappings:
        tactic = (m.tactic or "").lower().replace(" ", "_").replace("-", "_")
        if tactic:
            tags.append(f"attack.{tactic}")
        tags.append(f"attack.{m.technique_id.lower()}")
    # dedupe, preserve order
    seen = set()
    out: list[str] = []
    for t in tags:
        if t not in seen:
            seen.add(t)
            out.append(t)
    return out


def write_sigma_rule(bundle: AnalysisBundle, out_path: Path) -> Path:
    sample = bundle.sample
    sample_id = sample.get("sample_id") or "unknown_sample"
    detected = {m.technique_id for m in bundle.result.mappings}

    selections: list[str] = []
    if "T1059.001" in detected:
        selections.append(
            "  selection_powershell:\n"
            "    Image|endswith: '\\powershell.exe'\n"
            "    CommandLine|contains:\n"
            "      - '-enc'\n"
            "      - '-EncodedCommand'\n"
            "      - '-w hidden'\n"
            "      - 'DownloadString'"
        )
    if "T1218.005" in detected:
        selections.append(
            "  selection_mshta:\n"
            "    Image|endswith: '\\mshta.exe'"
        )
    if "T1490" in detected:
        selections.append(
            "  selection_vssadmin:\n"
            "    Image|endswith: '\\vssadmin.exe'\n"
            "    CommandLine|contains:\n"
            "      - 'delete shadows'\n"
            "      - 'delete catalog'"
        )
    if "T1547.001" in detected:
        selections.append(
            "  selection_runkey:\n"
            "    Image|endswith: '\\reg.exe'\n"
            "    CommandLine|contains:\n"
            "      - 'CurrentVersion\\Run'\n"
            "      - 'CurrentVersion\\RunOnce'"
        )
    if not selections:
        selections.append(
            "  selection_default:\n"
            "    Image|endswith:\n"
            "      - '\\powershell.exe'\n"
            "      - '\\mshta.exe'"
        )

    yaml_text = (
        f"title: AnalystBridge Behavior Detection - {sample.get('filename') or sample_id}\n"
        f"id: {_rule_uuid(sample_id)}\n"
        f"status: experimental\n"
        f"description: |\n"
        f"  Behavior-based detection generated by AnalystBridge from sample\n"
        f"  {sample.get('filename')} (sha256 {sample.get('sha256')}).\n"
        f"  Malice Score: {bundle.result.score.score} / {bundle.result.score.risk_level}.\n"
        f"references:\n"
        f"  - https://attack.mitre.org/\n"
        f"author: AnalystBridge\n"
        f"date: {utc_now_iso().split('T')[0].replace('-', '/')}\n"
        f"tags:\n"
        + "".join(f"  - {t}\n" for t in _attack_tags(bundle.result.mappings))
        + "logsource:\n"
        f"  category: process_creation\n"
        f"  product: windows\n"
        f"detection:\n"
        + "\n".join(selections) + "\n"
        f"  condition: 1 of selection_*\n"
        f"falsepositives:\n"
        f"  - Legitimate administrator scripting (verify with the host owner)\n"
        f"level: high\n"
    )
    out_path.write_text(yaml_text, encoding="utf-8")
    return out_path
